### ISSUE TITLE
An error had occurred

### ISSUE THREAD

**Issue by rwkw23** [jianhuupenn/TESLA#6]
enhanced_exp_adata.obs[g]=enhanced_exp_adata.X[:,enhanced_exp_adata.var.index==g]
Traceback (most recent call last):
  File "/home/ZRZ/miniconda3/envs/TESLA/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2895, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'CD151'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ZRZ/miniconda3/envs/TESLA/lib/python3.7/site-packages/pandas/core/generic.py", line 3574, in _set_item
    loc = self._info_axis.get_loc(key)
  File "/home/ZRZ/miniconda3/envs/TESLA/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2897, in get_loc
    raise KeyError(key) from err
KeyError: 'CD151'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ZRZ/miniconda3/envs/TESLA/lib/python3.7/site-packages/pandas/core/frame.py", line 3040, in __setitem__
    self._set_item(key, value)
  File "/home/ZRZ/miniconda3/envs/TESLA/lib/python3.7/site-packages/pandas/core/frame.py", line 3117, in _set_item
    NDFrame._set_item(self, key, value)
  File "/home/ZRZ/miniconda3/envs/TESLA/lib/python3.7/site-packages/pandas/core/generic.py", line 3577, in _set_item
    self._mgr.insert(len(self._info_axis), key, value)
  File "/home/ZRZ/miniconda3/envs/TESLA/lib/python3.7/site-packages/pandas/core/internals/managers.py", line 1189, in ins
ert    block = make_block(values=value, ndim=self.ndim, placement=slice(loc, loc + 1))
  File "/home/ZRZ/miniconda3/envs/TESLA/lib/python3.7/site-packages/pandas/core/internals/blocks.py", line 2722, in make_
block    return klass(values, ndim=ndim, placement=placement)
  File "/home/ZRZ/miniconda3/envs/TESLA/lib/python3.7/site-packages/pandas/core/internals/blocks.py", line 131, in __init
__    f"Wrong number of items passed {len(self.values)}, "
ValueError: Wrong number of items passed 0, placement implies 1

how can I solve this problem？

**Comment by jianhuupenn** [comment]
Thanks for your interest in our method.
It seems the gene "CD151" is not presented or filtered out in your original expression matrix.
I would suggest to check the expression of CD151 in your raw data.

**Comment by rwkw23** [comment]
> Thanks for your interest in our method. It seems the gene "CD151" is not presented or filtered out in your original expression matrix. I would suggest to check the expression of CD151 in your raw data.

Hello, I encountered the following error while running the tutorial you provided. Do you have any good solutions to this issue?

**Comment by Haz1y** [comment]
How can multiple structures like this be accurately segmented into individual contours rather than one, as it results in many empty spots in the filled area, such as the black region in the image below, where there is no organization detected and thus no RNA present?
<img width="688" alt="image" src="https://github.com/jianhuupenn/TESLA/assets/50012377/56c4b5af-1de7-4a9c-8058-ac87baff7088">
<img width="1201" alt="image" src="https://github.com/jianhuupenn/TESLA/assets/50012377/7f666bcd-4f97-422a-b3b7-7c700bed607c">
